name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker compose --env-file $HOME/venture-food-app/.env -f docker-compose-prod.yml up -d --build